/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as CommentsIndexRouteImport } from './routes/comments/index'
import { Route as PostsAllRouteImport } from './routes/posts/all'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as UsersUsernameIndexRouteImport } from './routes/users/$username/index'
import { Route as TopicsTopicSlugIndexRouteImport } from './routes/topics/$topicSlug/index'
import { Route as UsersUsernamePostsRouteImport } from './routes/users/$username/posts'
import { Route as UsersUsernameCommentsRouteImport } from './routes/users/$username/comments'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts/new'
import { Route as AuthenticatedPostsFollowingRouteImport } from './routes/_authenticated/posts/following'
import { Route as TopicsTopicSlugPostsIndexRouteImport } from './routes/topics/$topicSlug/posts/index'
import { Route as TopicsTopicSlugPostsPostIdRouteImport } from './routes/topics/$topicSlug/posts/$postId'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIndexRoute = CommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAllRoute = PostsAllRouteImport.update({
  id: '/posts/all',
  path: '/posts/all',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UsersUsernameIndexRoute = UsersUsernameIndexRouteImport.update({
  id: '/users/$username/',
  path: '/users/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicSlugIndexRoute = TopicsTopicSlugIndexRouteImport.update({
  id: '/topics/$topicSlug/',
  path: '/topics/$topicSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernamePostsRoute = UsersUsernamePostsRouteImport.update({
  id: '/users/$username/posts',
  path: '/users/$username/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameCommentsRoute = UsersUsernameCommentsRouteImport.update({
  id: '/users/$username/comments',
  path: '/users/$username/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsFollowingRoute =
  AuthenticatedPostsFollowingRouteImport.update({
    id: '/posts/following',
    path: '/posts/following',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const TopicsTopicSlugPostsIndexRoute =
  TopicsTopicSlugPostsIndexRouteImport.update({
    id: '/topics/$topicSlug/posts/',
    path: '/topics/$topicSlug/posts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicsTopicSlugPostsPostIdRoute =
  TopicsTopicSlugPostsPostIdRouteImport.update({
    id: '/topics/$topicSlug/posts/$postId',
    path: '/topics/$topicSlug/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/posts/all': typeof PostsAllRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/users': typeof UsersIndexRoute
  '/posts/following': typeof AuthenticatedPostsFollowingRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/users/$username/comments': typeof UsersUsernameCommentsRoute
  '/users/$username/posts': typeof UsersUsernamePostsRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/topics/$topicSlug/posts/$postId': typeof TopicsTopicSlugPostsPostIdRoute
  '/topics/$topicSlug/posts': typeof TopicsTopicSlugPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/posts/all': typeof PostsAllRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/users': typeof UsersIndexRoute
  '/posts/following': typeof AuthenticatedPostsFollowingRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/users/$username/comments': typeof UsersUsernameCommentsRoute
  '/users/$username/posts': typeof UsersUsernamePostsRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/topics/$topicSlug/posts/$postId': typeof TopicsTopicSlugPostsPostIdRoute
  '/topics/$topicSlug/posts': typeof TopicsTopicSlugPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/posts/all': typeof PostsAllRoute
  '/comments/': typeof CommentsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_authenticated/posts/following': typeof AuthenticatedPostsFollowingRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
  '/users/$username/comments': typeof UsersUsernameCommentsRoute
  '/users/$username/posts': typeof UsersUsernamePostsRoute
  '/topics/$topicSlug/': typeof TopicsTopicSlugIndexRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/topics/$topicSlug/posts/$postId': typeof TopicsTopicSlugPostsPostIdRoute
  '/topics/$topicSlug/posts/': typeof TopicsTopicSlugPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/posts/all'
    | '/comments'
    | '/posts'
    | '/topics'
    | '/users'
    | '/posts/following'
    | '/posts/new'
    | '/users/$username/comments'
    | '/users/$username/posts'
    | '/topics/$topicSlug'
    | '/users/$username'
    | '/topics/$topicSlug/posts/$postId'
    | '/topics/$topicSlug/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/posts/all'
    | '/comments'
    | '/posts'
    | '/topics'
    | '/users'
    | '/posts/following'
    | '/posts/new'
    | '/users/$username/comments'
    | '/users/$username/posts'
    | '/topics/$topicSlug'
    | '/users/$username'
    | '/topics/$topicSlug/posts/$postId'
    | '/topics/$topicSlug/posts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/settings'
    | '/_guest/login'
    | '/_guest/register'
    | '/posts/all'
    | '/comments/'
    | '/posts/'
    | '/topics/'
    | '/users/'
    | '/_authenticated/posts/following'
    | '/_authenticated/posts/new'
    | '/users/$username/comments'
    | '/users/$username/posts'
    | '/topics/$topicSlug/'
    | '/users/$username/'
    | '/topics/$topicSlug/posts/$postId'
    | '/topics/$topicSlug/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  PostsAllRoute: typeof PostsAllRoute
  CommentsIndexRoute: typeof CommentsIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUsernameCommentsRoute: typeof UsersUsernameCommentsRoute
  UsersUsernamePostsRoute: typeof UsersUsernamePostsRoute
  TopicsTopicSlugIndexRoute: typeof TopicsTopicSlugIndexRoute
  UsersUsernameIndexRoute: typeof UsersUsernameIndexRoute
  TopicsTopicSlugPostsPostIdRoute: typeof TopicsTopicSlugPostsPostIdRoute
  TopicsTopicSlugPostsIndexRoute: typeof TopicsTopicSlugPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/': {
      id: '/comments/'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/all': {
      id: '/posts/all'
      path: '/posts/all'
      fullPath: '/posts/all'
      preLoaderRoute: typeof PostsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/users/$username/': {
      id: '/users/$username/'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicSlug/': {
      id: '/topics/$topicSlug/'
      path: '/topics/$topicSlug'
      fullPath: '/topics/$topicSlug'
      preLoaderRoute: typeof TopicsTopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/posts': {
      id: '/users/$username/posts'
      path: '/users/$username/posts'
      fullPath: '/users/$username/posts'
      preLoaderRoute: typeof UsersUsernamePostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/comments': {
      id: '/users/$username/comments'
      path: '/users/$username/comments'
      fullPath: '/users/$username/comments'
      preLoaderRoute: typeof UsersUsernameCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/following': {
      id: '/_authenticated/posts/following'
      path: '/posts/following'
      fullPath: '/posts/following'
      preLoaderRoute: typeof AuthenticatedPostsFollowingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/topics/$topicSlug/posts/': {
      id: '/topics/$topicSlug/posts/'
      path: '/topics/$topicSlug/posts'
      fullPath: '/topics/$topicSlug/posts'
      preLoaderRoute: typeof TopicsTopicSlugPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicSlug/posts/$postId': {
      id: '/topics/$topicSlug/posts/$postId'
      path: '/topics/$topicSlug/posts/$postId'
      fullPath: '/topics/$topicSlug/posts/$postId'
      preLoaderRoute: typeof TopicsTopicSlugPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPostsFollowingRoute: typeof AuthenticatedPostsFollowingRoute
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPostsFollowingRoute: AuthenticatedPostsFollowingRoute,
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  PostsAllRoute: PostsAllRoute,
  CommentsIndexRoute: CommentsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersUsernameCommentsRoute: UsersUsernameCommentsRoute,
  UsersUsernamePostsRoute: UsersUsernamePostsRoute,
  TopicsTopicSlugIndexRoute: TopicsTopicSlugIndexRoute,
  UsersUsernameIndexRoute: UsersUsernameIndexRoute,
  TopicsTopicSlugPostsPostIdRoute: TopicsTopicSlugPostsPostIdRoute,
  TopicsTopicSlugPostsIndexRoute: TopicsTopicSlugPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
